#!/bin/bash

# This script is used to setup the environment for testing the UTHP on real hardware.
echo "Please ensure you are running this script on the post-production UTHP hardware (eMMC)."
echo "Also ensure the J1939 and J1708 buses are powered."
read -p "Are you connected to the Cascadia CAN bus and the Brake Board? (y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Nn]$ ]]; then
    echo -e "\nPlease connect to the Cascadia CAN bus and the Brake Board before running the tests."
    exit 1
elif [[ $EUID -ne 0 ]]; then
    echo -e "\nThis script must be run as root. Please run the script again with sudo."
    exit 1
else
    echo "Setting up the environment for testing the core uthp tests..."
    echo "====================================================="
    echo "Unique identifiers for $(hostname):"
	sudo lsblk -o NAME,UUID | grep "mmcblk1" -A 2
    echo "Setting up the CAN interface..."
    sudo ip link set can0 down
    sudo ip link set can0 type can bitrate 500000
    sudo ip link set up can0
    echo "Setting up the Brake Board..."
    # ensure the standard j1708 service is running and not the plc4trucks service
    sudo systemctl stop plc4trucksduck.service
    sudo systemctl stop j17084truckduck.service
    sudo systemctl start j17084truckduck.service
    echo "Environment setup should be complete... waiting for user to confirm hardware is ready."
    read -p "Press any key to continue..."
    echo "Starting the core uthp tests..."
fi
